### ISSUE TITLE
can't find hateful_meme_feature.py

### ISSUE THREAD

**Issue by hyqyoung** [HimariO/HatefulMemesChallenge#1]
Thanks for your great work! When I run run_feat_extract.sh, I can't find hateful_meme_feature.py in the origin library or in the library of py-bottom-up-attention.

**Comment by HimariO** [comment]
`hateful_meme_feature.py`  only exists in my custom version of the py-bottom-up-attention. You should find it at `/py-bottom-up-attention/demo/hateful_meme_feature.py`  if you are using [my docker image](https://hub.docker.com/repository/docker/dsfhe49854/py-bottom-up-attention).

**Comment by hyqyoung** [comment]
> `hateful_meme_feature.py` only exists in my custom version of the py-bottom-up-attention. You should find it at `/py-bottom-up-attention/demo/hateful_meme_feature.py` if you are using [my docker image](https://hub.docker.com/repository/docker/dsfhe49854/py-bottom-up-attention).

Thanks and it helps a lot

**Comment by nikhilbchilwant** [comment]
See here https://github.com/HimariO/py-bottom-up-attention/blob/package/demo/hateful_meme_feature.py
