### ISSUE TITLE
missing source code

### ISSUE THREAD

**Issue by zhangleihan** [HimariO/HatefulMemesChallenge#6]
Hi, May I ask that where can I find hateful_meme_feature.py used in run_feat_extract.sh. I cannot find the code in both this repo and py-bottom-up-attention.

**Comment by HimariO** [comment]
It is located in the `package` branch of the **py-bottom-up-attention** repo, you can find it over [here](https://github.com/HimariO/py-bottom-up-attention/blob/package/demo/hateful_meme_feature.py)
