### ISSUE TITLE
Use model for Feature Extraction

### ISSUE THREAD

**Issue by umbylyno** [HimariO/HatefulMemesChallenge#7]
Hello, everyone. 
First of all I would like to congratulate you for the fantastic work. 
I then wanted to ask if it was possible to have the fused features of any model before the classifier, and if so how to do it. 

Thank you in advance for your answers.

**Comment by HimariO** [comment]
Can you be more specific about what you trying to do? I'm having a hard time understanding what " fused features" mean. 🤔

**Comment by umbylyno** [comment]
Hi. Thanks for your reply. 
Basically I would like to extract the feature vector for each meme before it enters the classifier. 
I would like to do this for VILLA, for example.

**Comment by HimariO** [comment]
Yes, it is possible to extract the features from the multi-modal transfer before we feed them to the dense layer classifier. But since this project is building on top of multiple open-source implementations of transfer models, there isn't a universal way to do it. PyTorch's [forward function hook](https://pytorch.org/tutorials/beginner/former_torchies/nnft_tutorial.html#forward-and-backward-function-hooks) is one of the possible and easier ways to do this.

**Comment by umbylyno** [comment]
Thank you very much for your answers. Sorry to keep bothering you.
Ok so I read and loaded the checkpoint and the model, in this case UNITER:
```
from HatefulMemesChallenge.UNITER.model.vqa import UniterForITM

checkpoint = torch.load('final.pt_path')
model = UniterForITM.from_pretrained('model.json_path_in_logs', checkpoint, img_dim=2048, num_answer=1)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model.to(device)
```
I then defined this function taken from medium.com : 
```
class FeatureExtractor(nn.Module):
    def __init__(self, model: nn.Module, layers: Iterable[str]):
        super().__init__()
        self.model = model
        self.layers = layers
        self._features = {layer: torch.empty(0) for layer in layers}

        for layer_id in layers:
            layer = dict([*self.model.named_modules()])[layer_id]
            layer.register_forward_hook(self.save_outputs_hook(layer_id))

    def save_outputs_hook(self, layer_id: str) -> Callable:
        def fn(_, __, output):
            self._features[layer_id] = output
        return fn

    def forward(self, x: Tensor) -> Dict[str, Tensor]:
        _ = self.model(x, compute_loss=False)
        return self._features
```
So I should run this:
```
uniter_features = FeatureExtractor(model, layers=["uniter.pooler"])
features = uniter_features(x)

print({name: output.shape for name, output in features.items()})
```
where 'x' in "uniter_features" should be an element of the dataloader (or dictionary?). The problem is that I would need 
```
input_ids = batch['input_ids']
position_ids = batch['position_ids']
img_feat = batch['img_feat']
img_pos_feat = batch['img_pos_feat']
attn_masks = batch['attn_masks']
gather_index = batch['gather_index']
```
Where can I get this data from?

**Comment by HimariO** [comment]
As you mentioned, the input data for UNITER comes from the data loader which can be found in [test_meme_itm.py](https://github.com/HimariO/HatefulMemesChallenge/blob/main/UNITER/test_meme_itm.py#L77:L86). Which will load the feature created by the shell script [create_all_db.sh](https://github.com/HimariO/HatefulMemesChallenge/blob/main/UNITER/scripts/create_all_db.sh).
